# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/uni-sparkle-deploy/uni-sparkle
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
