# appspec.yml

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/uni-sparkle-deploy/uni-sparkle
    overwrite: yes

permissions:
  - object: /home/ubuntu/uni-sparkle-deploy/uni-sparkle/script
    pattern: "**"
    owner: ubuntu
    mode: 755
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/run_new.sh
      timeout: 180
      runas: ubuntu

    - location: scripts/health_check.sh
      timeout: 180
      runas: ubuntu

    - location: scripts/switch.sh
      timeout: 180
      runas: ubuntu
