name: On Push CI

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/gradle-task.yml
    with:
      tasks : '["checkstyleMain", "checkstyleTest", "build -x test", "test"]'
    secrets: inherit

  result-failure:
    needs:
      - ci
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: On Failed, Notify in Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Uni/Server Debug build Fail❌ 에러를 확인해주세요'
          SLACK_ICON: ${{ github.event.org.avatar_url }}
          MSG_MINIMAL: event,actions url, commit
          SLACK_USERNAME: Uni-server
          SLACK_MESSAGE: '${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number}}'
