name: Uni PR Builder

on:
  push:
    branches: [ develop, main ]

permissions:
  contents: read

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: load github submodule
        run: ./gradlew copyConfig

  checkstyle:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: load github submodule
        run: ./gradlew copyConfig

      - name: Checkstyle Check
        run: ./gradlew checkstyleMain checkstyleTest

  build:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: load github submodule
        run: ./gradlew copyConfig

      - name: Build with Gradle
        run: ./gradlew clean build

  test:
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: load github submodule
        run: ./gradlew copyConfig

      - name: Build with Gradle
        run: ./gradlew test

  result:
    needs:
      - checkstyle
      - build
      - test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: On Failed, Notify in Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: 'Uni/Server Debug build Fail❌ 에러를 확인해주세요'
          SLACK_ICON: ${{ github.event.org.avatar_url }}
          MSG_MINIMAL: event,actions url, commit
          SLACK_USERNAME: Uni-server
          SLACK_MESSAGE: '${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}'
