on:
  workflow_call:
    inputs:
      tasks:
        description: gradle execute option
        type: string

jobs:
  gradle-task:
    strategy:
      matrix:
        gradle: ${{ fromJSON(inputs.tasks) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}
          submodules: true

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load GitHub submodule
        run: ./gradlew copyConfig

      - name: Run Gradle Task
        run: ./gradle ${{matrix.gradle}}